#!/usr/bin/env bash
set -ex
shopt -s nullglob
tar xf src.tgz
exec >result.json
echo -n "{"
for test in tests/*.json; do
  for x in $(quickrun --list-contracts < $test); do
    if [[ "$x" =~ .Test$ ]]; then
      if [[ $i > 0 ]]; then echo -n ","; fi
      i=$((i+1))
      echo -n "\"$x\":"
      quickrun --test-contract=$x --logs --diff --trace --json < $test
    fi
  done
done
echo -n "}"
