#!/usr/bin/env bash
set -ex
git clone "$1" repo
git -C repo checkout -b rev "$2"

if [ -e repo/.gitmodules ]; then
  sed -i 's~git@github.com:~https://github.com/~' repo/.gitmodules
  git -C repo submodule update --init --recursive
fi

tar zcf rev.tgz repo
